-- EximNext Thailand Suppliers Data Import
-- Generated by insert_data.py

CREATE DATABASE IF NOT EXISTS shop_ai;
USE shop_ai;

CREATE TABLE IF NOT EXISTS suppliers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rating DECIMAL(3,2) DEFAULT 3.00,
    reliable BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight_kg DECIMAL(10,2) DEFAULT 1.00,
    selling_price_mmk DECIMAL(15,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS supplier_products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    supplier_id INT NOT NULL,
    product_id INT NOT NULL,
    price_thb DECIMAL(15,2) DEFAULT 100.00,
    moq INT DEFAULT 1,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS shipping_methods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cost_thb_per_kg DECIMAL(10,2) DEFAULT 50.00,
    delivery_days INT DEFAULT 7
);

-- Suppliers
INSERT INTO suppliers (id, name, rating, reliable) VALUES (1, 'F D & A Inter Co. Ltd.', 3.95, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (2, 'Suwancham Dairy Ltd', 3.95, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (3, 'Planet Silver Wholesale Jewelry', 3.9, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (4, 'Finixx Group', 4.05, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (5, 'Aureus Thai Group', 3.9, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (6, 'Supannee Trading Limited Partership', 3.9, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (7, 'Thiladee Sinlawan', 3.9, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (8, 'Big Star Co. Ltd.', 3.95, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (9, 'C.P. Intertrade Co., Ltd.', 3.5, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (10, 'MV Siam Limited', 4.05, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (11, 'Okura World Transport Co., Ltd.', 3.85, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (12, 'Khumsub Asia Goods Trading Co., Ltd.', 4.05, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (13, 'Mangmee Enterprise Company Limited', 3.95, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (14, 'Thai Peace Pulp (Thailand) Co., Ltd', 3.9, TRUE);
INSERT INTO suppliers (id, name, rating, reliable) VALUES (15, 'Ashirwad Trading Co. Ltd.', 3.85, TRUE);

-- Products
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (1, 'Copper Cathode', 18.73, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (2, 'Aluminium Scrap', 14.45, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (3, 'Aluminium Ingots', 17.44, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (4, 'Sunflower Oil', 1.94, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (5, 'Coconut Oil', 0.5, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (6, 'Olive Oil', 1.87, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (7, 'Soybean Oil', 0.9, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (8, 'Palm Oil', 0.68, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (9, 'Jasmin Rice', 1.77, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (10, 'Brown Rice', 1.53, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (11, 'Home Mali Rice', 1.57, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (12, 'Sugar', 0.79, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (13, 'Brown Sugar', 1.64, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (14, 'Red Kidney Beans', 1.49, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (15, 'Black Beans', 1.82, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (16, 'Shrimp', 1.25, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (17, 'Tilapia Fish', 0.73, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (18, 'Crabs', 1.99, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (19, 'Wires & Cables', 18.09, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (20, 'Organic Essential Oils', 1.03, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (21, 'Lucozade Energy Drink Orange', 0.9, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (22, 'Natural Power Energy Drink', 0.67, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (23, 'Sweetened Condensed Milk', 1.34, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (24, 'Kidney Beans', 0.77, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (25, 'Pimple and Whitening Soap', 0.5, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (26, 'White and Yellow Corn', 0.55, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (27, 'Refind White dust and Crystal Sugar', 1.55, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (28, 'A4 Copy Paper', 0.71, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (29, 'Best Quality Peanuts', 0.72, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (30, 'Barley', 0.99, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (31, 'Beans', 1.99, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (32, 'Original 100g Antiseptic Dettol Soap', 0.51, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (33, 'X3 OHO Glutathione Collagen Soap', 0.59, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (34, 'Fruity Pineapple and Papaya Natural Soap', 0.89, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (35, '100% Pure Thailand Milk', 0.66, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (36, 'Sterling Silver Rings', 0.7, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (37, 'Sterling Silver Necklaces', 0.49, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (38, 'Sterling Silver Bracelets', 0.2, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (39, 'Sterling Silver Earrings', 1.0, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (40, 'Silver Pendants', 0.6, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (41, 'Silver Charms', 0.63, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (42, 'Gemstone Jewelry', 0.37, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (43, 'Fashion Jewelry', 0.19, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (44, 'Wholesale Silver Jewelry', 0.29, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (45, 'Silver Sets', 0.99, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (46, 'Truck Tyres TBR', 0.69, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (47, 'OTR Tyres', 0.52, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (48, 'Industrial Tyres', 0.12, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (49, 'Agricultural Tyres', 0.42, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (50, 'Forklift Tyres', 0.74, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (51, 'Rubber Products', 0.85, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (52, 'Auto Parts', 0.4, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (53, 'Industrial Equipment', 0.41, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (54, 'Construction Materials', 0.35, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (55, 'Paras Gold Rice', 0.53, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (56, 'PR-11 Rice', 1.05, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (57, 'Thai Jasmine Rice', 0.69, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (58, 'Basmati Rice', 1.9, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (59, 'Sticky Rice', 1.29, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (60, 'Rice Products', 0.65, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (61, 'Thai Food Products', 1.33, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (62, 'Frozen Foods', 1.04, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (63, 'Snacks', 0.95, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (64, 'Beverages', 0.73, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (65, 'Seasonings', 0.12, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (66, 'Walnuts', 0.76, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (67, 'Chicken Feet', 1.93, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (68, 'Red Tilapia', 0.52, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (69, 'Seafood Products', 1.69, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (70, 'Canned Foods', 0.75, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (71, 'Thai Snacks', 1.05, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (72, 'Condiments', 0.18, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (73, 'Spices', 1.96, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (74, 'Nuts and Seeds', 0.59, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (75, 'Dried Foods', 1.02, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (76, 'Dried Grass Jelly Leaves', 0.55, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (77, 'Dried Reetha (Soapnut)', 0.82, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (78, 'Herbal Products', 0.96, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (79, 'Natural Products', 16.17, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (80, 'Organic Products', 16.72, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (81, 'Traditional Thai Products', 6.93, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (82, 'Drumsticks', 0.95, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (83, 'Leggings', 0.4, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (84, 'Trouser', 0.87, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (85, 'T-Shirts', 0.68, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (86, 'Shirts', 0.35, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (87, 'Jeans', 0.13, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (88, 'Jackets', 0.16, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (89, 'Sportswear', 0.19, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (90, 'Workwear', 0.46, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (91, 'Fashion Apparel', 0.68, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (92, 'Textiles', 0.84, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (93, 'Food Products', 0.83, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (94, 'Consumer Goods', 0.15, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (95, 'Household Items', 0.93, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (96, 'Personal Care Products', 0.31, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (97, 'Grocery Items', 0.1, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (98, 'Packaged Foods', 1.61, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (99, 'Vermi compost', 0.64, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (100, 'OCC waste paper', 0.39, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (101, 'Recycled paper', 0.81, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (102, 'Waste paper', 0.16, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (103, 'Paper Products', 0.33, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (104, 'Packaging Materials', 0.3, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (105, 'Recycling Materials', 0.67, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (106, 'Eco Products', 15.84, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (107, 'Dog Food', 1.02, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (108, 'Canned Items', 0.33, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (109, 'Pepsi Cans', 0.61, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (110, 'Snack Foods', 0.97, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (111, 'Pet Food', 0.72, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (112, 'Imported Foods', 1.78, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (113, 'Japanese Products', 6.94, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (114, 'Transportation Services', 0.23, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (115, 'Thai Curry Red Green Yellow', 1.39, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (116, 'Ethanol 96% Food Grade', 5.63, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (117, 'Ethanol 99% Sugarcane', 5.75, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (118, 'Ethanol Rice', 16.61, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (119, 'Chemical Products', 18.95, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (120, 'Food Additives', 1.7, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (121, 'Industrial Chemicals', 8.13, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (122, 'Organic Chemicals', 6.86, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (123, 'Raw Materials', 0.55, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (124, 'MCC PH102', 16.16, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (125, 'USB Polygraph Machine', 0.31, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (126, 'Alpha-Olefin Sulfonate AOS 92%', 8.98, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (127, 'Industrial Supplies', 0.43, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (128, 'Laboratory Equipment', 0.22, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (129, 'Testing Equipment', 13.36, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (130, 'Safety Equipment', 0.7, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (131, 'Freon R-417A Refrigerant Gas', 7.23, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (132, 'Continental Coach HA3 Tire', 0.13, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (133, 'Pampers Baby-Dry Diapers', 0.89, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (134, 'Paper Pulp', 0.71, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (135, 'Tissue Paper', 0.48, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (136, 'Hygiene Products', 0.37, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (137, 'Personal Care', 0.6, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (138, 'MARATHON SUPER G', 0.93, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (139, 'CGG 75mm', 0.25, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (140, 'CGG 50mm', 0.18, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (141, 'Industrial Products', 15.2, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (142, 'Building Supplies', 0.93, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (143, 'Hardware', 0.19, 0.0);
INSERT INTO products (id, name, weight_kg, selling_price_mmk) VALUES (144, 'Tools and Equipment', 0.34, 0.0);

-- Supplier-Product Links
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 1, 342.88, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 2, 101.06, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 3, 171.26, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 4, 122.68, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 5, 136.21, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 6, 140.94, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 7, 188.28, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 8, 93.82, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 9, 91.74, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 10, 79.06, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 11, 127.18, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 12, 61.35, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 13, 179.24, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 14, 79.38, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 15, 140.0, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 16, 126.55, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 17, 76.36, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 18, 97.15, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 19, 101.33, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (1, 20, 121.36, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 21, 81.38, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 22, 45.16, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 23, 67.75, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 24, 140.08, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 4, 64.18, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 25, 61.01, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 26, 52.75, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 27, 53.22, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 28, 23.43, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 29, 155.7, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 30, 191.62, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 31, 127.26, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 32, 54.57, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 33, 99.87, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 34, 31.17, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (2, 35, 188.01, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 36, 80.31, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 37, 66.23, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 38, 63.93, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 39, 94.17, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 40, 99.22, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 41, 35.63, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 42, 75.46, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 43, 69.42, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 44, 99.25, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (3, 45, 44.32, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 46, 88.29, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 47, 87.34, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 48, 37.14, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 49, 56.01, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 50, 34.55, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 51, 88.79, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 52, 41.17, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 53, 50.14, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (4, 54, 34.6, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 55, 140.83, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 56, 136.87, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 57, 60.58, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 58, 124.95, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 59, 68.21, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 60, 110.55, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 61, 171.41, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 62, 116.77, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 63, 128.86, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 64, 45.17, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (5, 65, 77.05, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 66, 110.88, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 67, 180.7, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 68, 137.03, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 69, 63.95, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 62, 128.42, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 70, 178.53, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 71, 183.15, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 72, 94.37, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 73, 120.36, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 74, 124.23, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (6, 75, 142.3, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 76, 37.02, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 77, 76.69, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 78, 171.51, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 79, 397.21, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 80, 247.87, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (7, 81, 442.16, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 82, 24.19, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 83, 93.15, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 84, 20.04, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 85, 24.12, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 86, 45.89, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 87, 26.8, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 88, 56.53, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 89, 92.28, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 90, 24.7, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 91, 35.78, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (8, 92, 50.92, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 93, 122.21, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 64, 99.24, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 94, 89.76, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 95, 33.87, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 96, 66.86, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 97, 96.77, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (9, 98, 100.28, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 99, 77.62, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 100, 97.77, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 101, 48.24, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 102, 69.45, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 103, 38.11, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 104, 33.16, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 105, 80.34, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (10, 106, 348.56, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 107, 70.2, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 108, 91.37, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 109, 94.81, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 64, 41.4, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 110, 190.27, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 111, 80.29, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 112, 99.18, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 113, 468.76, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (11, 114, 74.93, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 115, 138.11, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 116, 148.83, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 117, 374.8, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 118, 435.26, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 119, 432.61, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 120, 141.96, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 121, 486.37, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 122, 404.52, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (12, 123, 76.91, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 124, 199.93, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 125, 76.82, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 126, 255.34, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 119, 282.1, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 127, 42.41, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 128, 23.76, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 129, 230.98, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (13, 130, 46.91, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 131, 475.61, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 132, 64.83, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 133, 56.28, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 134, 76.32, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 135, 73.24, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 103, 36.15, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 136, 53.36, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (14, 137, 70.58, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 138, 68.02, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 139, 56.99, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 140, 97.89, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 141, 118.88, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 54, 85.97, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 142, 38.19, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 143, 56.04, 1);
INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) VALUES (15, 144, 62.47, 1);

-- Shipping Methods
INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('air_cargo', 150.00, 3);
INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('land_cargo', 30.00, 14);
INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('sea_cargo', 15.00, 30);