import csv
import os

CSV_FILE = os.path.join(os.path.dirname(__file__), "scraped_data.csv")
SQL_FILE = os.path.join(os.path.dirname(__file__), "import.sql")


def read_csv() -> list[dict]:
    rows = []
    with open(CSV_FILE, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    print(f"Read {len(rows)} rows from {CSV_FILE}")
    return rows


def main():
    print("=" * 50)
    print("  EximNext Data SQL Generator")
    print("=" * 50)

    if not os.path.exists(CSV_FILE):
        print(f"ERROR: {CSV_FILE} not found")
        print("Run scraper.py first to generate the data")
        return

    rows = read_csv()

    unique_suppliers = {}
    for row in rows:
        name = row["supplier_name"]
        if name not in unique_suppliers:
            unique_suppliers[name] = {
                "rating": float(row["rating"]),
                "trust_score": int(row["trust_score"]),
            }

    unique_products = {}
    for row in rows:
        name = row["product_name"]
        if name not in unique_products:
            unique_products[name] = {
                "weight_kg": float(row["weight_kg"]),
            }

    sql_lines = []
    sql_lines.append("-- EximNext Thailand Suppliers Data Import")
    sql_lines.append("-- Generated by insert_data.py\n")

    sql_lines.append("CREATE DATABASE IF NOT EXISTS shop_ai;")
    sql_lines.append("USE shop_ai;\n")

    sql_lines.append("""CREATE TABLE IF NOT EXISTS suppliers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    rating DECIMAL(3,2) DEFAULT 3.00,
    reliable BOOLEAN DEFAULT TRUE
);\n""")

    sql_lines.append("""CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight_kg DECIMAL(10,2) DEFAULT 1.00,
    selling_price_mmk DECIMAL(15,2) DEFAULT 0.00
);\n""")

    sql_lines.append("""CREATE TABLE IF NOT EXISTS supplier_products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    supplier_id INT NOT NULL,
    product_id INT NOT NULL,
    price_thb DECIMAL(15,2) DEFAULT 100.00,
    moq INT DEFAULT 1,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);\n""")

    sql_lines.append("""CREATE TABLE IF NOT EXISTS shipping_methods (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cost_thb_per_kg DECIMAL(10,2) DEFAULT 50.00,
    delivery_days INT DEFAULT 7
);\n""")

    sql_lines.append("-- Suppliers")
    for i, (name, data) in enumerate(unique_suppliers.items(), 1):
        safe_name = name.replace("'", "''")
        reliable = "TRUE" if data["trust_score"] >= 60 else "FALSE"
        sql_lines.append(
            f"INSERT INTO suppliers (id, name, rating, reliable) "
            f"VALUES ({i}, '{safe_name}', {data['rating']}, {reliable});"
        )

    sql_lines.append("\n-- Products")
    product_id_map = {}
    for i, (name, data) in enumerate(unique_products.items(), 1):
        safe_name = name.replace("'", "''")
        sql_lines.append(
            f"INSERT INTO products (id, name, weight_kg, selling_price_mmk) "
            f"VALUES ({i}, '{safe_name}', {data['weight_kg']}, 0.0);"
        )
        product_id_map[name] = i

    sql_lines.append("\n-- Supplier-Product Links")
    for i, row in enumerate(rows, 1):
        supplier_name = row["supplier_name"]
        product_name = row["product_name"]
        price_thb = float(row["price_thb"])
        moq = int(row["moq"])

        supplier_id = list(unique_suppliers.keys()).index(supplier_name) + 1
        product_id = product_id_map.get(product_name, 1)

        sql_lines.append(
            f"INSERT INTO supplier_products (supplier_id, product_id, price_thb, moq) "
            f"VALUES ({supplier_id}, {product_id}, {price_thb}, {moq});"
        )

    sql_lines.append("\n-- Shipping Methods")
    sql_lines.append("INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('air_cargo', 150.00, 3);")
    sql_lines.append("INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('land_cargo', 30.00, 14);")
    sql_lines.append("INSERT INTO shipping_methods (name, cost_thb_per_kg, delivery_days) VALUES ('sea_cargo', 15.00, 30);")

    with open(SQL_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nGenerated SQL file: {SQL_FILE}")
    print(f"  Suppliers: {len(unique_suppliers)}")
    print(f"  Products: {len(unique_products)}")
    print(f"  Supplier-Product Links: {len(rows)}")

    print("\n" + "=" * 50)
    print("  To import, run:")
    print(f"    mysql -u root < {SQL_FILE}")
    print("=" * 50)


if __name__ == "__main__":
    main()
